Breaking changes in librsync 1.0.0
With librsync 1.0.0, npm gives this error:

  CXX(target) Release/obj.target/rdiff/rdiff.o
../rdiff.cc: In function 'rs_result signature(const char*, const char*)':
../rdiff.cc:214:75: error: cannot convert 'rs_stats_t* {aka rs_stats*}' to 'rs_magic_number' for argument '5' to 'rs_result rs_sig_file(FILE*, FILE*, size_t, size_t, rs_magic_number, rs_stats_t*)'
   result = rs_sig_file(basis_file, sig_file, block_len, strong_len, &stats);
                                                                           ^
rdiff.target.mk:83: recipe for target 'Release/obj.target/rdiff/rdiff.o' failed
make: *** [Release/obj.target/rdiff/rdiff.o] Error 1